### ISSUE TITLE
Does no output mean that tests were successful?

### ISSUE THREAD

**Issue by akami-channel** [tBuLi/kingdon#34]
I ran python3 test_kingdon.py and there was no output to the terminal. It simply executed and then gave me my normal prompt again.

Does this mean that the test was successful? It would be nice to either have some output in the terminal or a description of expected behavior in the readme.

**Comment by tBuLi** [comment]
Make sure you have pytest installed, and then try running
```
pytest tests\test_kingdon.py
```
This should give you all the feedback you need :).
